// Wire contract between sluice-controller (control plane) and sluiced (data
// plane). One RPC, one direction: the controller pushes, the data plane only
// ever receives. See CLAUDE.md invariant "full state, never deltas" and
// docs/SPEC.md CP-U-03 — every BackendSet is the complete backend list, never
// an incremental update, so a data plane that reconnects after any outage
// self-heals with no special-case code.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: sluice/v1/config.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigStream_Watch_FullMethodName = "/sluice.v1.ConfigStream/Watch"
)

// ConfigStreamClient is the client API for ConfigStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigStreamClient interface {
	// Server-streaming: the data plane calls Watch once and keeps the stream
	// open for the life of the process. It receives the complete current
	// BackendSet immediately (SPEC.md CP-E-02), then one further BackendSet
	// per reconcile that actually changes the backend set (CP-E-01/CP-X-01).
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackendSet], error)
}

type configStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigStreamClient(cc grpc.ClientConnInterface) ConfigStreamClient {
	return &configStreamClient{cc}
}

func (c *configStreamClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackendSet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigStream_ServiceDesc.Streams[0], ConfigStream_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, BackendSet]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigStream_WatchClient = grpc.ServerStreamingClient[BackendSet]

// ConfigStreamServer is the server API for ConfigStream service.
// All implementations must embed UnimplementedConfigStreamServer
// for forward compatibility.
type ConfigStreamServer interface {
	// Server-streaming: the data plane calls Watch once and keeps the stream
	// open for the life of the process. It receives the complete current
	// BackendSet immediately (SPEC.md CP-E-02), then one further BackendSet
	// per reconcile that actually changes the backend set (CP-E-01/CP-X-01).
	Watch(*WatchRequest, grpc.ServerStreamingServer[BackendSet]) error
	mustEmbedUnimplementedConfigStreamServer()
}

// UnimplementedConfigStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigStreamServer struct{}

func (UnimplementedConfigStreamServer) Watch(*WatchRequest, grpc.ServerStreamingServer[BackendSet]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedConfigStreamServer) mustEmbedUnimplementedConfigStreamServer() {}
func (UnimplementedConfigStreamServer) testEmbeddedByValue()                      {}

// UnsafeConfigStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigStreamServer will
// result in compilation errors.
type UnsafeConfigStreamServer interface {
	mustEmbedUnimplementedConfigStreamServer()
}

func RegisterConfigStreamServer(s grpc.ServiceRegistrar, srv ConfigStreamServer) {
	// If the following call pancis, it indicates UnimplementedConfigStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigStream_ServiceDesc, srv)
}

func _ConfigStream_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigStreamServer).Watch(m, &grpc.GenericServerStream[WatchRequest, BackendSet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigStream_WatchServer = grpc.ServerStreamingServer[BackendSet]

// ConfigStream_ServiceDesc is the grpc.ServiceDesc for ConfigStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sluice.v1.ConfigStream",
	HandlerType: (*ConfigStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ConfigStream_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sluice/v1/config.proto",
}
