// Wire contract between sluice-controller (control plane) and sluiced (data
// plane). One RPC, one direction: the controller pushes, the data plane only
// ever receives. See CLAUDE.md invariant "full state, never deltas" and
// docs/SPEC.md CP-U-03 — every BackendSet is the complete backend list, never
// an incremental update, so a data plane that reconnects after any outage
// self-heals with no special-case code.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.36.0
// source: sluice/v1/config.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_sluice_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_sluice_v1_config_proto_rawDescGZIP(), []int{0}
}

type Backend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "ip:port" of a single backend pod.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_sluice_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_sluice_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BackendSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing config version (docs/SPEC.md "Config version").
	Version       uint64     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Backends      []*Backend `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendSet) Reset() {
	*x = BackendSet{}
	mi := &file_sluice_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendSet) ProtoMessage() {}

func (x *BackendSet) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendSet.ProtoReflect.Descriptor instead.
func (*BackendSet) Descriptor() ([]byte, []int) {
	return file_sluice_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *BackendSet) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackendSet) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

var File_sluice_v1_config_proto protoreflect.FileDescriptor

const file_sluice_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16sluice/v1/config.proto\x12\tsluice.v1\"\x0e\n" +
	"\fWatchRequest\"#\n" +
	"\aBackend\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"V\n" +
	"\n" +
	"BackendSet\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12.\n" +
	"\bbackends\x18\x02 \x03(\v2\x12.sluice.v1.BackendR\bbackends2I\n" +
	"\fConfigStream\x129\n" +
	"\x05Watch\x12\x17.sluice.v1.WatchRequest\x1a\x15.sluice.v1.BackendSet0\x01BDZBgithub.com/owenhochwald/sluice/sluice-controller/internal/genprotob\x06proto3"

var (
	file_sluice_v1_config_proto_rawDescOnce sync.Once
	file_sluice_v1_config_proto_rawDescData []byte
)

func file_sluice_v1_config_proto_rawDescGZIP() []byte {
	file_sluice_v1_config_proto_rawDescOnce.Do(func() {
		file_sluice_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sluice_v1_config_proto_rawDesc), len(file_sluice_v1_config_proto_rawDesc)))
	})
	return file_sluice_v1_config_proto_rawDescData
}

var file_sluice_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sluice_v1_config_proto_goTypes = []any{
	(*WatchRequest)(nil), // 0: sluice.v1.WatchRequest
	(*Backend)(nil),      // 1: sluice.v1.Backend
	(*BackendSet)(nil),   // 2: sluice.v1.BackendSet
}
var file_sluice_v1_config_proto_depIdxs = []int32{
	1, // 0: sluice.v1.BackendSet.backends:type_name -> sluice.v1.Backend
	0, // 1: sluice.v1.ConfigStream.Watch:input_type -> sluice.v1.WatchRequest
	2, // 2: sluice.v1.ConfigStream.Watch:output_type -> sluice.v1.BackendSet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sluice_v1_config_proto_init() }
func file_sluice_v1_config_proto_init() {
	if File_sluice_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sluice_v1_config_proto_rawDesc), len(file_sluice_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sluice_v1_config_proto_goTypes,
		DependencyIndexes: file_sluice_v1_config_proto_depIdxs,
		MessageInfos:      file_sluice_v1_config_proto_msgTypes,
	}.Build()
	File_sluice_v1_config_proto = out.File
	file_sluice_v1_config_proto_goTypes = nil
	file_sluice_v1_config_proto_depIdxs = nil
}
